FsNeedsSyncException=\n\
The cache entry is already present in the output archive.\n\
This is expected to be an aftermath of a previous attempt to sync() which\n\
failed with an FsNeedsLockRetryException from the parent controller when\n\
close() was called on the input or output archive for the target archive file.\n\
Hence, the following exception is regarded as superfluous and will get ignored.\n\
The integrity of the virtual file system should not be affected: